Adding unit tests to verify LogicalTypes support.
Tests fail e.g. due to:
java.lang.ClassCastException: class java.time.LocalTime cannot be cast to class java.lang.Integer